// This file is automatically generated from the types.json file
// Do not edit manually

export type WordType = 
  | "po"
  | "pt"
  | "puč"
  | "pks"
  | "př"
  | "pum"
  | "pkn"
  | "puz"
  | "pup"
  | "pu míry"
  | "d";