// This file is automatically generated from the types.json file
// Do not edit manually

export type WordType = 
  | "po"
  | "pt"
  | "puč"
  | "pks"
  | "př"
  | "pum"
  | "pkn"
  | "puz"
  | "pu příčiny"
  | "pu míry"
  | "d";

export const WORD_TYPES: WordType[] = [
  "po",
  "pt",
  "puč",
  "pks",
  "př",
  "pum",
  "pkn",
  "puz",
  "pu příčiny",
  "pu míry",
  "d"
]; 